### PR TITLE
Combine TAF lists

### PR DESCRIPTION
**Pull request by IvanaEscobar**
`F90list` is no longer necessary as a separate file. Added contents of `F90list` to `list` which determines which files are passed to TAF for generation of the adjoint model

### CODE REVIEW

**Comment by mjlosch** [comment]
I suggest to also remove `nobcs` in the `SIZE*.h` and break a long STORE directive line in two in `exf_geos_bulkf.F` to make it work "out of the box" with https://github.com/MITgcm/MITgcm/pull/709.

**Comment by IvanaEscobar** [comment]
NOTE: I checked this set-up with MITgcm `checkpoint 68z`. 

Made the changes suggested by @mjlosch

**Comment by mjlosch** [comment]
That's great, now this works with PR https://github.com/MITgcm/MITgcm/pull/709 for me without any modifications (just add a `FORTRAN_VERS_TAF='F90'` or `ALWAYS_USE_F90=1` to `genmake_local`)

**Comment by menemenlis** [comment]
Hi all, the repository is deprecated and has been replaced by: https://github.com/geos-mitgcm-ecco/gmao_mitgcm_coupling
Ivan and Martin, would it be possible to move this discussion to the new repo?
Let me know if either or both of you want write access to the new repo.
Thanks, Dimitris

**Comment by IvanaEscobar** [comment]
@menemenlis @mjlosch 

Transferred PR to active repo: [Active PR](https://github.com/geos-mitgcm-ecco/gmao_mitgcm_coupling/pull/1)

**Pull request closed without merging**
